name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
        with:
          vs-version: [16.5]

    - name: Build
      run: msbuild windows-touchpad.sln
